In [1]:
import pandas as pd
import numpy as np

data = {
    "Shipment_ID": [1001, 1002, 1003, 1004, 1005, 1005, 1006, 1007],
    "Customer": [
        "Amazon",
        "Zalando",
        "amazon",
        "Otto",
        "Amazon",
        "Amazon",
        "Zalando",
        "OTTO"
    ],
    "Revenue": [1200, 850, 1500, np.nan, 2100, 2100, 950, 1100],
    "Delivery_Days": [2, 4, 3, 1, np.nan, np.nan, 2, 3],
    "Status": [
        "Delivered",
        "Delivered",
        "Delayed",
        "Delivered",
        "delayed",
        "delayed",
        "Delivered",
        "Delivered"
    ]
}

shipments = pd.DataFrame(data)

shipments

   Shipment_ID Customer  Revenue  Delivery_Days     Status
0         1001   Amazon   1200.0            2.0  Delivered
1         1002  Zalando    850.0            4.0  Delivered
2         1003   amazon   1500.0            3.0    Delayed
3         1004     Otto      NaN            1.0  Delivered
4         1005   Amazon   2100.0            NaN    delayed
5         1005   Amazon   2100.0            NaN    delayed
6         1006  Zalando    950.0            2.0  Delivered
7         1007     OTTO   1100.0            3.0  Delivered

In [2]:
shipments["Revenue"].isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
Name: Revenue, dtype: bool

### Exercise 02.03.01 — Detect Missing Values

In [3]:
shipments.isna().sum()

Shipment_ID      0
Customer         0
Revenue          1
Delivery_Days    2
Status           0
dtype: int64

### Exercise 02.03.02 — Handling Missing Values

In [4]:
median_delivery = shipments["Delivery_Days"].median()

In [5]:
shipments["Delivery_Days"] = shipments["Delivery_Days"].fillna(median_delivery)
shipments

   Shipment_ID Customer  Revenue  Delivery_Days     Status
0         1001   Amazon   1200.0            2.0  Delivered
1         1002  Zalando    850.0            4.0  Delivered
2         1003   amazon   1500.0            3.0    Delayed
3         1004     Otto      NaN            1.0  Delivered
4         1005   Amazon   2100.0            2.5    delayed
5         1005   Amazon   2100.0            2.5    delayed
6         1006  Zalando    950.0            2.0  Delivered
7         1007     OTTO   1100.0            3.0  Delivered

In [6]:
shipments.isna().sum()

Shipment_ID      0
Customer         0
Revenue          1
Delivery_Days    0
Status           0
dtype: int64

In [7]:
shipments[shipments["Delivery_Days"] == 2.5]

   Shipment_ID Customer  Revenue  Delivery_Days   Status
4         1005   Amazon   2100.0            2.5  delayed
5         1005   Amazon   2100.0            2.5  delayed

### Exercise 02.03.04 — Handling Missing Revenue

In [8]:
missing_revenue = shipments[shipments["Revenue"].isna()]
missing_revenue

   Shipment_ID Customer  Revenue  Delivery_Days     Status
3         1004     Otto      NaN            1.0  Delivered

### Exercise 02.03.05 — Detecting Duplicate Rec

In [9]:
shipments.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [10]:
shipments.duplicated(subset=["Shipment_ID"])

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [11]:
duplicated_id = shipments[shipments["Shipment_ID"].duplicated()]
duplicated_id

   Shipment_ID Customer  Revenue  Delivery_Days   Status
5         1005   Amazon   2100.0            2.5  delayed

### Exercise 02.03.06 — Removing Duplicates

In [12]:
shipments = shipments.drop_duplicates(subset=["Shipment_ID"])

print(shipments)
print(shipments.shape[0])

   Shipment_ID Customer  Revenue  Delivery_Days     Status
0         1001   Amazon   1200.0            2.0  Delivered
1         1002  Zalando    850.0            4.0  Delivered
2         1003   amazon   1500.0            3.0    Delayed
3         1004     Otto      NaN            1.0  Delivered
4         1005   Amazon   2100.0            2.5    delayed
6         1006  Zalando    950.0            2.0  Delivered
7         1007     OTTO   1100.0            3.0  Delivered
7

### Exercise 02.03.07 — Standardizing Customer Names

In [13]:
shipments

   Shipment_ID Customer  Revenue  Delivery_Days     Status
0         1001   Amazon   1200.0            2.0  Delivered
1         1002  Zalando    850.0            4.0  Delivered
2         1003   amazon   1500.0            3.0    Delayed
3         1004     Otto      NaN            1.0  Delivered
4         1005   Amazon   2100.0            2.5    delayed
6         1006  Zalando    950.0            2.0  Delivered
7         1007     OTTO   1100.0            3.0  Delivered

In [14]:
shipments["Customer"].value_counts()

Customer
Amazon     2
Zalando    2
amazon     1
Otto       1
OTTO       1
Name: count, dtype: int64

In [15]:
shipments["Customer"] = shipments["Customer"].str.title()

shipments["Customer"].value_counts()

Customer
Amazon     3
Zalando    2
Otto       2
Name: count, dtype: int64

### Exercise 02.03.08 — Cleaning Whitespace and Text Formatting

In [16]:
shipments.loc[0, "Customer"] = " Amazon "
shipments.loc[1, "Customer"] = " zalando"
shipments.loc[3, "Customer"] = "OTTO "

In [17]:
shipments["Customer"].tolist()

[' Amazon ', ' zalando', 'Amazon', 'OTTO ', 'Amazon', 'Zalando', 'Otto']

In [18]:
shipments["Customer"] = shipments["Customer"].str.strip().str.title()

In [19]:
shipments["Customer"].value_counts()

Customer
Amazon     3
Zalando    2
Otto       2
Name: count, dtype: int64

### Exercise 02.03.09 — Correcting Data Types

In [20]:
shipments["Revenue"] = shipments["Revenue"].astype("string")

shipments.dtypes

Shipment_ID        int64
Customer             str
Revenue           string
Delivery_Days    float64
Status               str
dtype: object

In [21]:
shipments

   Shipment_ID Customer Revenue  Delivery_Days     Status
0         1001   Amazon  1200.0            2.0  Delivered
1         1002  Zalando   850.0            4.0  Delivered
2         1003   Amazon  1500.0            3.0    Delayed
3         1004     Otto    <NA>            1.0  Delivered
4         1005   Amazon  2100.0            2.5    delayed
6         1006  Zalando   950.0            2.0  Delivered
7         1007     Otto  1100.0            3.0  Delivered

In [22]:
shipments["Revenue"] = shipments["Revenue"].astype("float")
shipments["Revenue"].dtype

dtype('float64')

In [23]:
shipments["Revenue"] = pd.to_numeric(
    shipments["Revenue"],
    errors="coerce"
)

shipments["Revenue"]

0    1200.0
1     850.0
2    1500.0
3       NaN
4    2100.0
6     950.0
7    1100.0
Name: Revenue, dtype: float64

## Exercise 02.03.10 — Final Data Cleaning Challenge
Today, you’ll apply everything you’ve learned to a realistic logistics dataset.

Your role: Data Analyst at a logistics company.

Business scenario: Your manager has received a shipment report from several operational systems. Before the data can be used for financial reporting and operational KPIs, you need to ensure its quality.

Unlike our previous exercises, I won’t provide the complete solution upfront. You’ll develop the cleaning process yourself, one task at a time.

In [24]:
import pandas as pd
import numpy as np

raw_data = {
    "Shipment_ID": [
        2001, 2002, 2003, 2004, 2005,
        2005, 2006, 2007, 2008, 2009
    ],
    "Customer": [
        "Amazon",
        " zalando ",
        "AMAZON",
        "Otto",
        "Zalando",
        "Zalando",
        " otto ",
        "Amazon ",
        "OTTO",
        "zalando"
    ],
    "Revenue": [
        "1200", "850", "unknown", "650", "2100",
        "2100", "950", "1750", None, "1100"
    ],
    "Delivery_Days": [
        2, 4, 3, np.nan, 5,
        5, 2, np.nan, 3, 4
    ],
    "Status": [
        "Delivered",
        "delivered",
        "Delayed",
        "Delivered",
        "Delayed",
        "Delayed",
        " delivered ",
        "DELAYED",
        "Delivered",
        "delivered"
    ]
}

raw_shipments = pd.DataFrame(raw_data)

raw_shipments

   Shipment_ID   Customer  Revenue  Delivery_Days       Status
0         2001     Amazon     1200            2.0    Delivered
1         2002   zalando       850            4.0    delivered
2         2003     AMAZON  unknown            3.0      Delayed
3         2004       Otto      650            NaN    Delivered
4         2005    Zalando     2100            5.0      Delayed
5         2005    Zalando     2100            5.0      Delayed
6         2006      otto       950            2.0   delivered
7         2007    Amazon      1750            NaN      DELAYED
8         2008       OTTO      NaN            3.0    Delivered
9         2009    zalando     1100            4.0    delivered

## Data Cleaning Challenge: Shipments

Your objective is to produce a cleaned DataFrame called `cleaned_shipments`.

The final dataset should satisfy the following requirements:

| Requirement | Expected Result |
|---|---|
| Preserve the original dataset | `raw_shipments` remains unchanged |
| Remove duplicate shipment IDs | 9 unique shipments |
| Standardize customer names | `Amazon`, `Zalando`, `Otto` |
| Standardize shipment statuses | `Delivered`, `Delayed` |
| Convert revenue to numerical values | Invalid values become `NaN` |
| Handle missing delivery times | Replace with median |
| Preserve unknown revenue | Do not invent financial values |
| Verify data quality | Check missing values, duplicates, and data types |

### Important

**Do not overwrite `raw_shipments`.**

We want to preserve the original dataset so we can compare it with the cleaned version.

In [25]:
cleaned_shipments = raw_shipments.copy()

In [26]:
cleaned_shipments.isna().sum()

Shipment_ID      0
Customer         0
Revenue          1
Delivery_Days    2
Status           0
dtype: int64

In [27]:
cleaned_shipments

   Shipment_ID   Customer  Revenue  Delivery_Days       Status
0         2001     Amazon     1200            2.0    Delivered
1         2002   zalando       850            4.0    delivered
2         2003     AMAZON  unknown            3.0      Delayed
3         2004       Otto      650            NaN    Delivered
4         2005    Zalando     2100            5.0      Delayed
5         2005    Zalando     2100            5.0      Delayed
6         2006      otto       950            2.0   delivered
7         2007    Amazon      1750            NaN      DELAYED
8         2008       OTTO      NaN            3.0    Delivered
9         2009    zalando     1100            4.0    delivered

In [28]:
cleaned_shipments.duplicated
cleaned_shipments = cleaned_shipments.drop_duplicates(subset=["Shipment_ID"])

In [29]:
median_delivery = cleaned_shipments["Delivery_Days"].median()
cleaned_shipments["Delivery_Days"] = cleaned_shipments["Delivery_Days"].fillna(median_delivery)

In [30]:
cleaned_shipments["Customer"]

0       Amazon
1     zalando
2       AMAZON
3         Otto
4      Zalando
6        otto
7      Amazon
8         OTTO
9      zalando
Name: Customer, dtype: str

In [31]:
cleaned_shipments["Customer"] = cleaned_shipments["Customer"].str.title().str.strip()

In [32]:
cleaned_shipments

   Shipment_ID Customer  Revenue  Delivery_Days       Status
0         2001   Amazon     1200            2.0    Delivered
1         2002  Zalando      850            4.0    delivered
2         2003   Amazon  unknown            3.0      Delayed
3         2004     Otto      650            3.0    Delivered
4         2005  Zalando     2100            5.0      Delayed
6         2006     Otto      950            2.0   delivered
7         2007   Amazon     1750            3.0      DELAYED
8         2008     Otto      NaN            3.0    Delivered
9         2009  Zalando     1100            4.0    delivered

In [33]:
cleaned_shipments["Status"].value_counts()

Status
Delivered      3
delivered      2
Delayed        2
 delivered     1
DELAYED        1
Name: count, dtype: int64

In [34]:
cleaned_shipments["Status"] = cleaned_shipments["Status"].str.title().str.strip()

In [35]:
cleaned_shipments["Status"].value_counts()

Status
Delivered    6
Delayed      3
Name: count, dtype: int64

In [36]:
cleaned_shipments["Revenue"] = pd.to_numeric(cleaned_shipments["Revenue"],errors="coerce")

In [37]:
cleaned_shipments

   Shipment_ID Customer  Revenue  Delivery_Days     Status
0         2001   Amazon   1200.0            2.0  Delivered
1         2002  Zalando    850.0            4.0  Delivered
2         2003   Amazon      NaN            3.0    Delayed
3         2004     Otto    650.0            3.0  Delivered
4         2005  Zalando   2100.0            5.0    Delayed
6         2006     Otto    950.0            2.0  Delivered
7         2007   Amazon   1750.0            3.0    Delayed
8         2008     Otto      NaN            3.0  Delivered
9         2009  Zalando   1100.0            4.0  Delivered

In [38]:
cleaned_shipments.isna().sum()

Shipment_ID      0
Customer         0
Revenue          2
Delivery_Days    0
Status           0
dtype: int64

In [39]:
print("Raw dataset:", raw_shipments.shape)
print("Cleaned dataset:", cleaned_shipments.shape)

print("\nDuplicate IDs:")
print(cleaned_shipments["Shipment_ID"].duplicated().sum())

print("\nMissing values:")
print(cleaned_shipments.isna().sum())

print("\nData types:")
print(cleaned_shipments.dtypes)

print("\nMedian delivery time:")
print(cleaned_shipments["Delivery_Days"].median())

Raw dataset: (10, 5)
Cleaned dataset: (9, 5)

Duplicate IDs:
0

Missing values:
Shipment_ID      0
Customer         0
Revenue          2
Delivery_Days    0
Status           0
dtype: int64

Data types:
Shipment_ID        int64
Customer             str
Revenue          float64
Delivery_Days    float64
Status               str
dtype: object

Median delivery time:
3.0

In [40]:
print(cleaned_shipments.loc[
    cleaned_shipments["Shipment_ID"].isin([2004, 2007]),
    ["Shipment_ID", "Delivery_Days"]
])

   Shipment_ID  Delivery_Days
3         2004            3.0
7         2007            3.0