In [1]:
import pandas as pd

print(pd.__version__)

3.0.6

In [2]:
revenues = pd.Series([12000, 18000, 14000])

In [3]:
print(revenues)
print(type(revenues))
print(revenues.shape)

0    12000
1    18000
2    14000
dtype: int64
<class 'pandas.Series'>
(3,)

In [4]:
data = {
    "City": ["Berlin", "Hamburg", "Munich"],
    "Revenue": [12000, 18000, 14000],
    "Shipments": [150, 220, 175],
    "Operating_Costs": [3000, 5400, 2800]
}

df = pd.DataFrame(data)

df

      City  Revenue  Shipments  Operating_Costs
0   Berlin    12000        150             3000
1  Hamburg    18000        220             5400
2   Munich    14000        175             2800

In [5]:
city = df["City"]
city

0     Berlin
1    Hamburg
2     Munich
Name: City, dtype: str

In [6]:
city_shipments = df[["City","Shipments"]]
city_shipments

      City  Shipments
0   Berlin        150
1  Hamburg        220
2   Munich        175

In [7]:
print(city.shape)

print(city_shipments.shape)

(3,)
(3, 2)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             3 non-null      str
 1   Revenue          3 non-null      int64
 2   Shipments        3 non-null      int64
 3   Operating_Costs  3 non-null      int64
dtypes: int64(3), str(1)
memory usage: 228.0 bytes

In [9]:
df.describe()

            Revenue   Shipments  Operating_Costs
count      3.000000    3.000000         3.000000
mean   14666.666667  181.666667      3733.333333
std     3055.050463   35.472994      1446.835628
min    12000.000000  150.000000      2800.000000
25%    13000.000000  162.500000      2900.000000
50%    14000.000000  175.000000      3000.000000
75%    16000.000000  197.500000      4200.000000
max    18000.000000  220.000000      5400.000000

In [10]:
df.describe(include="all")

          City       Revenue   Shipments  Operating_Costs
count        3      3.000000    3.000000         3.000000
unique       3           NaN         NaN              NaN
top     Berlin           NaN         NaN              NaN
freq         1           NaN         NaN              NaN
mean       NaN  14666.666667  181.666667      3733.333333
std        NaN   3055.050463   35.472994      1446.835628
min        NaN  12000.000000  150.000000      2800.000000
25%        NaN  13000.000000  162.500000      2900.000000
50%        NaN  14000.000000  175.000000      3000.000000
75%        NaN  16000.000000  197.500000      4200.000000
max        NaN  18000.000000  220.000000      5400.000000

### Shipments Import

In [11]:
shipments = pd.read_csv("shipments.csv")

shipments.head()

   Shipment_ID     City Customer  Revenue  Delivery_Days     Status
0         1001   Berlin   Amazon     1200              2  Delivered
1         1002  Hamburg  Zalando      850              4  Delivered
2         1003   Munich   Amazon     1500              3    Delayed
3         1004   Berlin     Otto      650              1  Delivered
4         1005  Hamburg   Amazon     2100              5    Delayed

In [12]:
shipments.shape

(8, 6)

In [13]:
shipments.dtypes

Shipment_ID      int64
City               str
Customer           str
Revenue          int64
Delivery_Days    int64
Status             str
dtype: object

In [14]:
shipments.describe()

       Shipment_ID     Revenue  Delivery_Days
count      8.00000     8.00000       8.000000
mean    1004.50000  1262.50000       3.250000
std        2.44949   488.25491       1.669046
min     1001.00000   650.00000       1.000000
25%     1002.75000   925.00000       2.000000
50%     1004.50000  1150.00000       3.000000
75%     1006.25000  1562.50000       4.250000
max     1008.00000  2100.00000       6.000000

In [15]:
shipments.iloc[2]

Shipment_ID         1003
City              Munich
Customer          Amazon
Revenue             1500
Delivery_Days          3
Status           Delayed
Name: 2, dtype: object

In [16]:
shipments.loc[0:2,["Customer","Revenue"]]

  Customer  Revenue
0   Amazon     1200
1  Zalando      850
2   Amazon     1500

In [17]:
shipments.iloc[0:5]

   Shipment_ID     City Customer  Revenue  Delivery_Days     Status
0         1001   Berlin   Amazon     1200              2  Delivered
1         1002  Hamburg  Zalando      850              4  Delivered
2         1003   Munich   Amazon     1500              3    Delayed
3         1004   Berlin     Otto      650              1  Delivered
4         1005  Hamburg   Amazon     2100              5    Delayed

In [18]:
shipments.iloc[4,3]

np.int64(2100)

In [19]:
shipments[shipments["Status"] == "Delayed"]

   Shipment_ID     City Customer  Revenue  Delivery_Days   Status
2         1003   Munich   Amazon     1500              3  Delayed
4         1005  Hamburg   Amazon     2100              5  Delayed
7         1008  Hamburg  Zalando     1750              6  Delayed

In [20]:
shipments.loc[shipments["Status"] == "Delayed"]

   Shipment_ID     City Customer  Revenue  Delivery_Days   Status
2         1003   Munich   Amazon     1500              3  Delayed
4         1005  Hamburg   Amazon     2100              5  Delayed
7         1008  Hamburg  Zalando     1750              6  Delayed

### Which shipments generated more than €1,000 in revenue?

In [21]:
shipments[shipments["Revenue"] > 1000]

   Shipment_ID     City Customer  Revenue  Delivery_Days     Status
0         1001   Berlin   Amazon     1200              2  Delivered
2         1003   Munich   Amazon     1500              3    Delayed
4         1005  Hamburg   Amazon     2100              5    Delayed
6         1007   Berlin     Otto     1100              3  Delivered
7         1008  Hamburg  Zalando     1750              6    Delayed

### Identify High-Value Delayed Shipments

In [22]:
delayed_high_shipments = shipments[
    (shipments["Revenue"] > 1000) &
    (shipments["Status"] == "Delayed")
]
delayed_high_shipments

   Shipment_ID     City Customer  Revenue  Delivery_Days   Status
2         1003   Munich   Amazon     1500              3  Delayed
4         1005  Hamburg   Amazon     2100              5  Delayed
7         1008  Hamburg  Zalando     1750              6  Delayed

In [23]:
delayed_high_shipments.shape

(3, 6)

In [24]:
delayed_high_shipments.shape[0]

3

### AND vs. OR

In [25]:
delayed_more_than_4 = shipments[
    (shipments["Status"] == "Delayed") |
    (shipments["Delivery_Days"] > 4)
]

In [26]:
delayed_more_than_4.shape[0]

3

### Sorting & Ranking

In [27]:
shipments.sort_values(by="Revenue", ascending=False).head()

   Shipment_ID     City Customer  Revenue  Delivery_Days     Status
4         1005  Hamburg   Amazon     2100              5    Delayed
7         1008  Hamburg  Zalando     1750              6    Delayed
2         1003   Munich   Amazon     1500              3    Delayed
0         1001   Berlin   Amazon     1200              2  Delivered
6         1007   Berlin     Otto     1100              3  Delivered

In [28]:
shipments[["Shipment_ID","Customer","Revenue"]].sort_values(by="Revenue", ascending=False).head()

   Shipment_ID Customer  Revenue
4         1005   Amazon     2100
7         1008  Zalando     1750
2         1003   Amazon     1500
0         1001   Amazon     1200
6         1007     Otto     1100

In [29]:
shipments.sort_values(by="Revenue", ascending=False).head()[["Shipment_ID","Customer","Revenue"]]

   Shipment_ID Customer  Revenue
4         1005   Amazon     2100
7         1008  Zalando     1750
2         1003   Amazon     1500
0         1001   Amazon     1200
6         1007     Otto     1100

### Creating Calculated Columns

In [30]:
shipments["Operating_Costs"] = shipments["Revenue"] * 0.30

In [31]:
shipments.sort_values(by = "Operating_Costs", ascending = False)

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0
7,1008,Hamburg,Zalando,1750,6,Delayed,525.0
2,1003,Munich,Amazon,1500,3,Delayed,450.0
0,1001,Berlin,Amazon,1200,2,Delivered,360.0
6,1007,Berlin,Otto,1100,3,Delivered,330.0
5,1006,Munich,Zalando,950,2,Delivered,285.0
1,1002,Hamburg,Zalando,850,4,Delivered,255.0
3,1004,Berlin,Otto,650,1,Delivered,195.0

In [32]:
shipments["Profit"] = shipments["Revenue"] - shipments["Operating_Costs"]
shipments["Profit_Margin"] = shipments["Profit"] / shipments["Revenue"] *100

In [33]:
shipments[["Profit","Profit_Margin"]].sort_values(by = "Profit", ascending = False).head()

   Profit  Profit_Margin
4  1470.0           70.0
7  1225.0           70.0
2  1050.0           70.0
0   840.0           70.0
6   770.0           70.0

### Data Types & Dates

In [34]:
shipments["Shipment_Date"] = [
    "2026-10-01",
    "2026-10-02",
    "2026-10-03",
    "2026-10-04",
    "2026-10-05",
    "2026-10-06",
    "2026-10-07",
    "2026-10-08"
]

In [35]:
shipments

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs,Profit,Profit_Margin,Shipment_Date
0,1001,Berlin,Amazon,1200,2,Delivered,360.0,840.0,70.0,2026-10-01
1,1002,Hamburg,Zalando,850,4,Delivered,255.0,595.0,70.0,2026-10-02
2,1003,Munich,Amazon,1500,3,Delayed,450.0,1050.0,70.0,2026-10-03
3,1004,Berlin,Otto,650,1,Delivered,195.0,455.0,70.0,2026-10-04
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0,1470.0,70.0,2026-10-05
5,1006,Munich,Zalando,950,2,Delivered,285.0,665.0,70.0,2026-10-06
6,1007,Berlin,Otto,1100,3,Delivered,330.0,770.0,70.0,2026-10-07
7,1008,Hamburg,Zalando,1750,6,Delayed,525.0,1225.0,70.0,2026-10-08

In [36]:
shipments["Shipment_Date"] = pd.to_datetime(shipments["Shipment_Date"])
shipments

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs,Profit,Profit_Margin,Shipment_Date
0,1001,Berlin,Amazon,1200,2,Delivered,360.0,840.0,70.0,2026-10-01
1,1002,Hamburg,Zalando,850,4,Delivered,255.0,595.0,70.0,2026-10-02
2,1003,Munich,Amazon,1500,3,Delayed,450.0,1050.0,70.0,2026-10-03
3,1004,Berlin,Otto,650,1,Delivered,195.0,455.0,70.0,2026-10-04
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0,1470.0,70.0,2026-10-05
5,1006,Munich,Zalando,950,2,Delivered,285.0,665.0,70.0,2026-10-06
6,1007,Berlin,Otto,1100,3,Delivered,330.0,770.0,70.0,2026-10-07
7,1008,Hamburg,Zalando,1750,6,Delayed,525.0,1225.0,70.0,2026-10-08

In [37]:
shipments["Weekday"] = shipments["Shipment_Date"].dt.day_name()
shipments

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs,Profit,Profit_Margin,Shipment_Date,Weekday
0,1001,Berlin,Amazon,1200,2,Delivered,360.0,840.0,70.0,2026-10-01,Thursday
1,1002,Hamburg,Zalando,850,4,Delivered,255.0,595.0,70.0,2026-10-02,Friday
2,1003,Munich,Amazon,1500,3,Delayed,450.0,1050.0,70.0,2026-10-03,Saturday
3,1004,Berlin,Otto,650,1,Delivered,195.0,455.0,70.0,2026-10-04,Sunday
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0,1470.0,70.0,2026-10-05,Monday
5,1006,Munich,Zalando,950,2,Delivered,285.0,665.0,70.0,2026-10-06,Tuesday
6,1007,Berlin,Otto,1100,3,Delivered,330.0,770.0,70.0,2026-10-07,Wednesday
7,1008,Hamburg,Zalando,1750,6,Delayed,525.0,1225.0,70.0,2026-10-08,Thursday

In [38]:
shipments[["Shipment_Date", "Weekday"]]

  Shipment_Date    Weekday
0    2026-10-01   Thursday
1    2026-10-02     Friday
2    2026-10-03   Saturday
3    2026-10-04     Sunday
4    2026-10-05     Monday
5    2026-10-06    Tuesday
6    2026-10-07  Wednesday
7    2026-10-08   Thursday

### Exporting Data

In [39]:
df.to_excel(
    "Data_Analysis_Shipments.xlsx",
    sheet_name="Shipment Analysis",
    index=False
)

In [40]:
top_5_profitable_shipments = shipments[["Shipment_ID","Customer","Revenue","Profit","Profit_Margin"]].sort_values(by = "Profit", ascending = False).head()

In [41]:
top_5_profitable_shipments.to_csv(
    "top_5_profitable_shipments.csv",
    index = False
)

### Final Pandas Fundamentals Challenge

How many shipments are in the dataset?

In [42]:
print(f"There are {shipments.shape[0]} in the dataset")

There are 8 in the dataset

What is the total revenue?

In [43]:
print(f"The total revenue is {shipments["Revenue"].sum()}€")

The total revenue is 10100€

What is the average delivery time?

In [44]:
print(f"The average delivery time is {shipments["Delivery_Days"].mean()} days")

The average delivery time is 3.25 days

How many shipments were delayed?

In [50]:
shipments[shipments["Status"] == "Delayed"].shape[0]

3

Which delayed shipment generated the highest profit?

In [70]:
shipments[shipments["Status"] == "Delayed"].sort_values(by = "Profit", ascending = False).head(1)

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs,Profit,Profit_Margin,Shipment_Date,Weekday
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0,1470.0,70.0,2026-10-05,Monday

Which shipments generated more than €1,000 profit?

In [59]:
shipments[shipments["Profit"] > 1000]

,Shipment_ID,City,Customer,Revenue,Delivery_Days,Status,Operating_Costs,Profit,Profit_Margin,Shipment_Date,Weekday
2,1003,Munich,Amazon,1500,3,Delayed,450.0,1050.0,70.0,2026-10-03,Saturday
4,1005,Hamburg,Amazon,2100,5,Delayed,630.0,1470.0,70.0,2026-10-05,Monday
7,1008,Hamburg,Zalando,1750,6,Delayed,525.0,1225.0,70.0,2026-10-08,Thursday

What is the overall profit margin?

In [69]:
print(f"The overall Profit Margin is {(shipments["Profit"].sum())/(shipments["Revenue"].sum())*100}")

The overall Profit Margin is 70.0

Export the delayed shipments as a CSV report

In [66]:
delayed_shipments = shipments[shipments["Status"] == "Delayed"]

delayed_shipments.to_csv(
    "delayed_shipments.csv",
    index = False
)